version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-apache
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    command: ./vendor/bin/phpunit
    depends_on:
      - db
volumes:
  db_data: